import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: "t101",
    firstName: "Adarsh",
    lastName: "Balika",
    username: "adarshbalika",
    password: "adarshBalika123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t102",
    firstName: "Manan",
    lastName: "Khurana",
    username: "manankhurana",
    password: "manan",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t103",
    firstName: "Naval",
    lastName: "Ravikant",
    username: "navalravikant",
    password: "naval",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t104",
    firstName: "Elon",
    lastName: "Musk",
    username: "elonmusk",
    password: "tesla123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t105",
    firstName: "Satya",
    lastName: "Nadella",
    username: "satyanadella",
    password: "microsoft",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t106",
    firstName: "Tim",
    lastName: "Cook",
    username: "timcook",
    password: "apple",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t107",
    firstName: "Jeff",
    lastName: "Bezos",
    username: "jeffbezos",
    password: "amazon",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t108",
    firstName: "Sundar",
    lastName: "Pichai",
    username: "sundarpichai",
    password: "google",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t109",
    firstName: "Mark",
    lastName: "Zuckerberg",
    username: "markzuckerberg",
    password: "facebook",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t110",
    firstName: "Jack",
    lastName: "Dorsey",
    username: "jackdorsey",
    password: "twitter",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t111",
    firstName: "Bill",
    lastName: "Gates",
    username: "billgates",
    password: "microsoft123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t112",
    firstName: "Gary",
    lastName: "Vaynerchuk",
    username: "garyvee",
    password: "winetasting",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t113",
    firstName: "Trevor",
    lastName: "Noah",
    username: "trevornoah",
    password: "dailyshow",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t114",
    firstName: "Hasan",
    lastName: "Minhaj",
    username: "hasanminhaj",
    password: "patriotact",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "t115",
    firstName: "Kunal",
    lastName: "Shah",
    username: "kunalshah",
    password: "razorpay",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
